name: Deploy static site with Jekyll blog

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby for Jekyll
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - name: Install Jekyll
        run: |
          gem install jekyll

      - name: Copy root static site into _site
        run: |
          # Copy everything except the Jekyll source under blog/
          rsync -av --delete \
            --exclude '.git' \
            --exclude '_site' \
            --exclude 'blog/' \
            --exclude '.github' \
            ./ _site/

      - name: Build blog (subdirectory)
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          if [[ "$REPO_NAME" == *.github.io ]]; then
            BASEURL="/blog"
          else
            BASEURL="/$REPO_NAME/blog"
          fi
          echo "Using baseurl=$BASEURL"
          jekyll build --source blog --destination _site/blog --baseurl "$BASEURL"

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
